### ISSUE TITLE
How to derive the weight of the joint from the weight of the bone？

### ISSUE THREAD

**Issue by dclcs** [elrond79/pmHeatWeight#1]
With this plugin, I can only get the weight of the bones. What I need now is the weight of each joint point. Is there any way to solve it?

**Comment by pmolodo** [comment]
First: this plugin is now obsolete. Maya now has built in support for heat weighting, check the options when binding

Second: Joints / bones are terms that can be used interchangeably, when talking about what object you want to assign weights to. (Maya doesn't really have "bones", just joints.)
